package cn.ssy.base.entity.mybatis;

public class TspTranController {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.system_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String systemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.corporate_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String corporateCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.tran_group_id
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String tranGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.step_id
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private Integer stepId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.tran_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String tranCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.tran_chinese_name
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String tranChineseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.execution_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String executionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.rely_tran_list
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String relyTranList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.tran_run_conditions
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String tranRunConditions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.reconnection_num
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private Integer reconnectionNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.fail_interrupt_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String failInterruptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.transactions_submit_num
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private Integer transactionsSubmitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.data_split_mode
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String dataSplitMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.job_execution_mode
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String jobExecutionMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.max_job_concurrency_num
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private Integer maxJobConcurrencyNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.log_level
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private Integer logLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.job_split_condition
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String jobSplitCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.task_run_mode
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String taskRunMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.is_skip
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String isSkip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.is_batch_file
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String isBatchFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.tran_type
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String tranType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_tran_controller.data_split_key
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    private String dataSplitKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.system_code
     *
     * @return the value of tsp_tran_controller.system_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getSystemCode() {
        return systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.system_code
     *
     * @param systemCode the value for tsp_tran_controller.system_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setSystemCode(String systemCode) {
        this.systemCode = systemCode == null ? null : systemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.corporate_code
     *
     * @return the value of tsp_tran_controller.corporate_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getCorporateCode() {
        return corporateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.corporate_code
     *
     * @param corporateCode the value for tsp_tran_controller.corporate_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setCorporateCode(String corporateCode) {
        this.corporateCode = corporateCode == null ? null : corporateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.tran_group_id
     *
     * @return the value of tsp_tran_controller.tran_group_id
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getTranGroupId() {
        return tranGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.tran_group_id
     *
     * @param tranGroupId the value for tsp_tran_controller.tran_group_id
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setTranGroupId(String tranGroupId) {
        this.tranGroupId = tranGroupId == null ? null : tranGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.step_id
     *
     * @return the value of tsp_tran_controller.step_id
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public Integer getStepId() {
        return stepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.step_id
     *
     * @param stepId the value for tsp_tran_controller.step_id
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setStepId(Integer stepId) {
        this.stepId = stepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.tran_code
     *
     * @return the value of tsp_tran_controller.tran_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getTranCode() {
        return tranCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.tran_code
     *
     * @param tranCode the value for tsp_tran_controller.tran_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setTranCode(String tranCode) {
        this.tranCode = tranCode == null ? null : tranCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.tran_chinese_name
     *
     * @return the value of tsp_tran_controller.tran_chinese_name
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getTranChineseName() {
        return tranChineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.tran_chinese_name
     *
     * @param tranChineseName the value for tsp_tran_controller.tran_chinese_name
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setTranChineseName(String tranChineseName) {
        this.tranChineseName = tranChineseName == null ? null : tranChineseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.execution_code
     *
     * @return the value of tsp_tran_controller.execution_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getExecutionCode() {
        return executionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.execution_code
     *
     * @param executionCode the value for tsp_tran_controller.execution_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setExecutionCode(String executionCode) {
        this.executionCode = executionCode == null ? null : executionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.rely_tran_list
     *
     * @return the value of tsp_tran_controller.rely_tran_list
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getRelyTranList() {
        return relyTranList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.rely_tran_list
     *
     * @param relyTranList the value for tsp_tran_controller.rely_tran_list
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setRelyTranList(String relyTranList) {
        this.relyTranList = relyTranList == null ? null : relyTranList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.tran_run_conditions
     *
     * @return the value of tsp_tran_controller.tran_run_conditions
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getTranRunConditions() {
        return tranRunConditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.tran_run_conditions
     *
     * @param tranRunConditions the value for tsp_tran_controller.tran_run_conditions
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setTranRunConditions(String tranRunConditions) {
        this.tranRunConditions = tranRunConditions == null ? null : tranRunConditions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.reconnection_num
     *
     * @return the value of tsp_tran_controller.reconnection_num
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public Integer getReconnectionNum() {
        return reconnectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.reconnection_num
     *
     * @param reconnectionNum the value for tsp_tran_controller.reconnection_num
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setReconnectionNum(Integer reconnectionNum) {
        this.reconnectionNum = reconnectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.fail_interrupt_code
     *
     * @return the value of tsp_tran_controller.fail_interrupt_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getFailInterruptCode() {
        return failInterruptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.fail_interrupt_code
     *
     * @param failInterruptCode the value for tsp_tran_controller.fail_interrupt_code
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setFailInterruptCode(String failInterruptCode) {
        this.failInterruptCode = failInterruptCode == null ? null : failInterruptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.transactions_submit_num
     *
     * @return the value of tsp_tran_controller.transactions_submit_num
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public Integer getTransactionsSubmitNum() {
        return transactionsSubmitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.transactions_submit_num
     *
     * @param transactionsSubmitNum the value for tsp_tran_controller.transactions_submit_num
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setTransactionsSubmitNum(Integer transactionsSubmitNum) {
        this.transactionsSubmitNum = transactionsSubmitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.data_split_mode
     *
     * @return the value of tsp_tran_controller.data_split_mode
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getDataSplitMode() {
        return dataSplitMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.data_split_mode
     *
     * @param dataSplitMode the value for tsp_tran_controller.data_split_mode
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setDataSplitMode(String dataSplitMode) {
        this.dataSplitMode = dataSplitMode == null ? null : dataSplitMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.job_execution_mode
     *
     * @return the value of tsp_tran_controller.job_execution_mode
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getJobExecutionMode() {
        return jobExecutionMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.job_execution_mode
     *
     * @param jobExecutionMode the value for tsp_tran_controller.job_execution_mode
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setJobExecutionMode(String jobExecutionMode) {
        this.jobExecutionMode = jobExecutionMode == null ? null : jobExecutionMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.max_job_concurrency_num
     *
     * @return the value of tsp_tran_controller.max_job_concurrency_num
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public Integer getMaxJobConcurrencyNum() {
        return maxJobConcurrencyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.max_job_concurrency_num
     *
     * @param maxJobConcurrencyNum the value for tsp_tran_controller.max_job_concurrency_num
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setMaxJobConcurrencyNum(Integer maxJobConcurrencyNum) {
        this.maxJobConcurrencyNum = maxJobConcurrencyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.log_level
     *
     * @return the value of tsp_tran_controller.log_level
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public Integer getLogLevel() {
        return logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.log_level
     *
     * @param logLevel the value for tsp_tran_controller.log_level
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setLogLevel(Integer logLevel) {
        this.logLevel = logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.job_split_condition
     *
     * @return the value of tsp_tran_controller.job_split_condition
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getJobSplitCondition() {
        return jobSplitCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.job_split_condition
     *
     * @param jobSplitCondition the value for tsp_tran_controller.job_split_condition
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setJobSplitCondition(String jobSplitCondition) {
        this.jobSplitCondition = jobSplitCondition == null ? null : jobSplitCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.task_run_mode
     *
     * @return the value of tsp_tran_controller.task_run_mode
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getTaskRunMode() {
        return taskRunMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.task_run_mode
     *
     * @param taskRunMode the value for tsp_tran_controller.task_run_mode
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setTaskRunMode(String taskRunMode) {
        this.taskRunMode = taskRunMode == null ? null : taskRunMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.is_skip
     *
     * @return the value of tsp_tran_controller.is_skip
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getIsSkip() {
        return isSkip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.is_skip
     *
     * @param isSkip the value for tsp_tran_controller.is_skip
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setIsSkip(String isSkip) {
        this.isSkip = isSkip == null ? null : isSkip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.is_batch_file
     *
     * @return the value of tsp_tran_controller.is_batch_file
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getIsBatchFile() {
        return isBatchFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.is_batch_file
     *
     * @param isBatchFile the value for tsp_tran_controller.is_batch_file
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setIsBatchFile(String isBatchFile) {
        this.isBatchFile = isBatchFile == null ? null : isBatchFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.tran_type
     *
     * @return the value of tsp_tran_controller.tran_type
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getTranType() {
        return tranType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.tran_type
     *
     * @param tranType the value for tsp_tran_controller.tran_type
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setTranType(String tranType) {
        this.tranType = tranType == null ? null : tranType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_tran_controller.data_split_key
     *
     * @return the value of tsp_tran_controller.data_split_key
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public String getDataSplitKey() {
        return dataSplitKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_tran_controller.data_split_key
     *
     * @param dataSplitKey the value for tsp_tran_controller.data_split_key
     *
     * @mbg.generated Sat Aug 17 11:47:00 CST 2019
     */
    public void setDataSplitKey(String dataSplitKey) {
        this.dataSplitKey = dataSplitKey == null ? null : dataSplitKey.trim();
    }

	@Override
	public String toString() {
		return "TspTranController [systemCode=" + systemCode + ", corporateCode=" + corporateCode + ", tranGroupId=" + tranGroupId + ", stepId=" + stepId + ", tranCode="
				+ tranCode + ", tranChineseName=" + tranChineseName + ", executionCode=" + executionCode + ", relyTranList=" + relyTranList + ", tranRunConditions="
				+ tranRunConditions + ", reconnectionNum=" + reconnectionNum + ", failInterruptCode=" + failInterruptCode + ", transactionsSubmitNum=" + transactionsSubmitNum
				+ ", dataSplitMode=" + dataSplitMode + ", jobExecutionMode=" + jobExecutionMode + ", maxJobConcurrencyNum=" + maxJobConcurrencyNum + ", logLevel=" + logLevel
				+ ", jobSplitCondition=" + jobSplitCondition + ", taskRunMode=" + taskRunMode + ", isSkip=" + isSkip + ", isBatchFile=" + isBatchFile + ", tranType=" + tranType
				+ ", dataSplitKey=" + dataSplitKey + "]";
	}
}